namespace IBApi.Orders
{
    public enum OrderType
    {
        Limit,
        Market,
        MarketWithProtection,
        RequestToQuote,
        Stop,
        StopLimit,
        MarketToLimit,
        MarketIfTouched,
        LimitIfTouched,
        TrailingStop,
        TrailingStopLimit,
        TrailingLimitIfTouched,
        TrailingMarketIfTouched,
        Relative,
        RetailPriceImprovement,
        MarketOnClose,
        MarketOnOpen,
        LimitOnClose,
        LimitOnOpen,
        PeggedToBenchmark,
        PeggedToMarket,
        PeggedToMidpoint,
        BoxTop,
        Vwap,
        GoodAfterTimeDate,
        GoodTillDateTime,
        GoodTillCanceled,
        ImmediateOrCancel,
        OneCancelsAll,
        Volatility
    }
}